[0m15:56:55.488491 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107a6cdc0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108d2f0d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108d2e9b0>]}


============================== 15:56:55.491729 | 5e8dcc4e-3b70-4487-a785-0d45e7811309 ==============================
[0m15:56:55.491729 [info ] [MainThread]: Running with dbt=1.9.1
[0m15:56:55.492125 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/melissaguzman/.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt clean', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:56:55.492662 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/melissaguzman/cybergirl/healthcare_readmission_pipeline/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:56:55.501450 [debug] [MainThread]: Resource report: {"command_name": "clean", "command_success": false, "command_wall_clock_time": 0.055629335, "process_in_blocks": "0", "process_kernel_time": 0.092296, "process_mem_max_rss": "95617024", "process_out_blocks": "0", "process_user_time": 0.69181}
[0m15:56:55.501916 [debug] [MainThread]: Command `dbt clean` failed at 15:56:55.501838 after 0.06 seconds
[0m15:56:55.502197 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107a6cdc0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108d2f970>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108d2f940>]}
[0m15:56:55.502520 [debug] [MainThread]: Flushing usage events
[0m15:56:55.943866 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:47:25.851032 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110908d90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111f2f0d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111f2e9b0>]}


============================== 12:47:25.854150 | a4c0fc57-9206-40c5-8ee7-4ff1281e3c85 ==============================
[0m12:47:25.854150 [info ] [MainThread]: Running with dbt=1.9.1
[0m12:47:25.854542 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': '/Users/melissaguzman/.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:47:25.864749 [info ] [MainThread]: dbt version: 1.9.1
[0m12:47:25.865063 [info ] [MainThread]: python version: 3.10.13
[0m12:47:25.865265 [info ] [MainThread]: python path: /Users/melissaguzman/cybergirl/healthcare_readmission_pipeline/venv/bin/python3.10
[0m12:47:25.865471 [info ] [MainThread]: os info: macOS-14.4.1-arm64-arm-64bit
[0m12:47:25.868904 [info ] [MainThread]: Error importing adapter: No module named 'dbt.adapters.snowflake'
[0m12:47:25.886593 [info ] [MainThread]: Using profiles dir at /Users/melissaguzman/.dbt
[0m12:47:25.887072 [info ] [MainThread]: Using profiles.yml file at /Users/melissaguzman/.dbt/profiles.yml
[0m12:47:25.887323 [info ] [MainThread]: Using dbt_project.yml file at /Users/melissaguzman/cybergirl/healthcare_readmission_pipeline/dbt_project.yml
[0m12:47:25.887531 [info ] [MainThread]: Configuration:
[0m12:47:25.887714 [info ] [MainThread]:   profiles.yml file [[31mERROR invalid[0m]
[0m12:47:25.887898 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m12:47:25.888067 [info ] [MainThread]: Required dependencies:
[0m12:47:25.888290 [debug] [MainThread]: Executing "git --help"
[0m12:47:25.899162 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--super-prefix=<path>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m12:47:25.899914 [debug] [MainThread]: STDERR: "b''"
[0m12:47:25.900166 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m12:47:25.900523 [info ] [MainThread]: Connection test skipped since no profile was found
[0m12:47:25.900901 [info ] [MainThread]: [31m2 checks failed:[0m
[0m12:47:25.901110 [info ] [MainThread]: Could not load dbt_project.yml
Profile loading failed for the following reason:
Runtime Error
  Credentials in profile "data_pipeline", target "dev" invalid: Runtime Error
    Could not find adapter type snowflake!

Runtime Error
  Credentials in profile "hrrp_dbt", target "dev" invalid: 'schemas_and_paths' is a required property


[0m12:47:25.901303 [info ] [MainThread]: Project loading failed for the following reason:
 project path </Users/melissaguzman/cybergirl/healthcare_readmission_pipeline/dbt_project.yml> not found

[0m12:47:25.907656 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.100780666, "process_in_blocks": "0", "process_kernel_time": 0.111104, "process_mem_max_rss": "96927744", "process_out_blocks": "0", "process_user_time": 0.726872}
[0m12:47:25.908696 [debug] [MainThread]: Command `dbt debug` failed at 12:47:25.908592 after 0.10 seconds
[0m12:47:25.909172 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110908d90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11203b910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11203aec0>]}
[0m12:47:25.909552 [debug] [MainThread]: Flushing usage events
[0m12:47:26.641303 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:50:16.948679 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105b48d30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106873070>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106872950>]}


============================== 12:50:16.952184 | 1fd8cc62-3097-4ef5-831e-fb5e8f2f25b6 ==============================
[0m12:50:16.952184 [info ] [MainThread]: Running with dbt=1.9.1
[0m12:50:16.952669 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/Users/melissaguzman/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:50:16.963440 [info ] [MainThread]: dbt version: 1.9.1
[0m12:50:16.963744 [info ] [MainThread]: python version: 3.10.13
[0m12:50:16.963948 [info ] [MainThread]: python path: /Users/melissaguzman/cybergirl/healthcare_readmission_pipeline/venv/bin/python3.10
[0m12:50:16.964141 [info ] [MainThread]: os info: macOS-14.4.1-arm64-arm-64bit
[0m12:50:16.967554 [info ] [MainThread]: Error importing adapter: No module named 'dbt.adapters.snowflake'
[0m12:50:16.981197 [info ] [MainThread]: Using profiles dir at /Users/melissaguzman/.dbt
[0m12:50:16.981596 [info ] [MainThread]: Using profiles.yml file at /Users/melissaguzman/.dbt/profiles.yml
[0m12:50:16.981879 [info ] [MainThread]: Using dbt_project.yml file at /Users/melissaguzman/cybergirl/healthcare_readmission_pipeline/dbt_project.yml
[0m12:50:16.982078 [info ] [MainThread]: Configuration:
[0m12:50:16.982255 [info ] [MainThread]:   profiles.yml file [[31mERROR invalid[0m]
[0m12:50:16.982424 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m12:50:16.982594 [info ] [MainThread]: Required dependencies:
[0m12:50:16.982806 [debug] [MainThread]: Executing "git --help"
[0m12:50:16.993854 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--super-prefix=<path>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m12:50:16.994553 [debug] [MainThread]: STDERR: "b''"
[0m12:50:16.994834 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m12:50:16.995318 [info ] [MainThread]: Connection test skipped since no profile was found
[0m12:50:16.995699 [info ] [MainThread]: [31m2 checks failed:[0m
[0m12:50:16.995927 [info ] [MainThread]: Could not load dbt_project.yml
Profile loading failed for the following reason:
Runtime Error
  Credentials in profile "data_pipeline", target "dev" invalid: Runtime Error
    Could not find adapter type snowflake!

Runtime Error
  Credentials in profile "hrrp_dbt", target "dev" invalid: 'schemas_and_paths' is a required property


[0m12:50:16.996139 [info ] [MainThread]: Project loading failed for the following reason:
 project path </Users/melissaguzman/cybergirl/healthcare_readmission_pipeline/dbt_project.yml> not found

[0m12:50:16.998119 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.094476044, "process_in_blocks": "0", "process_kernel_time": 0.126644, "process_mem_max_rss": "97583104", "process_out_blocks": "0", "process_user_time": 0.790655}
[0m12:50:16.998759 [debug] [MainThread]: Command `dbt debug` failed at 12:50:16.998684 after 0.10 seconds
[0m12:50:16.999094 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105b48d30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106983910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106982e60>]}
[0m12:50:16.999385 [debug] [MainThread]: Flushing usage events
[0m12:50:17.564239 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:11:39.049725 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108080d60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108ff3340>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108ff2c20>]}


============================== 15:11:39.053233 | 1c4d411c-4136-40b1-b57c-a3531320e68c ==============================
[0m15:11:39.053233 [info ] [MainThread]: Running with dbt=1.9.1
[0m15:11:39.053642 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/melissaguzman/.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt test', 'send_anonymous_usage_stats': 'True'}
[0m15:11:39.054010 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/melissaguzman/cybergirl/healthcare_readmission_pipeline/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:11:39.054805 [debug] [MainThread]: Resource report: {"command_name": "test", "command_success": false, "command_wall_clock_time": 0.04301529, "process_in_blocks": "0", "process_kernel_time": 0.073308, "process_mem_max_rss": "97484800", "process_out_blocks": "0", "process_user_time": 0.683184}
[0m15:11:39.055095 [debug] [MainThread]: Command `dbt test` failed at 15:11:39.055040 after 0.04 seconds
[0m15:11:39.055321 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108080d60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108ff2290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108ff32e0>]}
[0m15:11:39.055535 [debug] [MainThread]: Flushing usage events
[0m15:11:39.382847 [debug] [MainThread]: An error was encountered while trying to flush usage events
